CREATE TABLE todo (
    id         UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    title      TEXT NOT NULL
);

CREATE TABLE item (
    id         UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
    todo_id    UUID REFERENCES todo(id),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    title      TEXT NOT NULL
);